### ISSUE TITLE
Q: multiplatform file operations lib?

### ISSUE THREAD

**Issue by 4ntoine** [AAkira/Kotlin-Multiplatform-Libraries#12]
What library can be used to read file content in unified way (shared code) on jvm and mac for example?

**Comment by AAkira** [comment]
I'm sorry. 
I don't know yet.
Please send a PR if you know.

FYI: 
#11 
I guess this library is for file I/O.
But I can't use it and it isn't an open source project.

**Comment by AAkira** [comment]
The work for MPP is now in progress in the okio.
#14
