### ISSUE TITLE
Cant create PR

### ISSUE THREAD

**Issue by Reedyuk** [AAkira/Kotlin-Multiplatform-Libraries#16]
Hi, I cant push my branch of your repo and so i cannot create a PR with my changes.

I'm trying to add this library:

```
#### Bluetooth

* [Blue-Falcon](https://github.com/Reedyuk/blue-falcon) - A unified Bluetooth library for Android and iOS 
![badge][badge-android]
![badge][badge-native]
```

**Comment by AAkira** [comment]
I have no idea.🤔
Did you fork this repository? 

I'll add it if you don't care about the contributor.
