### ISSUE TITLE
Multiplatform-LiveData - wrong listing

### ISSUE THREAD

**Issue by MarcusWolschon** [AAkira/Kotlin-Multiplatform-Libraries#20]
"Multiplatform-LiveData" is listed as native + Android while it is iOS and Android.
It does not support Kotlin/native (Linux, Windows,...)

**Comment by AAkira** [comment]
Thank you for reporting.
I know some libraries have a mix of Kotlin/Native and iOS.
I'll fix it when I have time 👍
