### ISSUE TITLE
Add nodejs platform

### ISSUE THREAD

**Issue by y9san9** [AAkira/Kotlin-Multiplatform-Libraries#70]
Hi, my library has a specialized target for nodejs, maybe some other libraries have it too. Would you provide such preset?

How it may look like: https://github.com/y9san9/kds/blob/master/README.md

The badge: [badge-nodejs]: http://img.shields.io/badge/platform-nodejs-68a063.svg?style=flat

**Comment by AAkira** [comment]
I added it!

**Comment by y9san9** [comment]
Thank you!
